### ISSUE TITLE
Bot ignores pm commands from power roles

### ISSUE THREAD

**Issue by Bazinga9000** [foolmoron/MafiaBot#1]
I created a mafia game with cops and vigilantes, and all players told me that the --scan command and the --kill command in pms failed to do anything.

**Comment by foolmoron** [comment]
:open_mouth: How did you even use the bot? It's not quite ready for public use I think, it's still just for my personal use and on our mafia server (discord.me/mafia). But I can try to help...

Are you running the bot locally? Does the console say anything or have any errors? This is a pretty broad issue so I'm not sure where it is failing. Was it night time? Night commands only work at night.
Did they get a PM for their role when you started the game?

**Comment by Bazinga9000** [comment]
The way i used the bot was i downloaded and extracted the zip and installed all the node.js dependencies within then ran it in the node.js console.

The console showed no errors at all at any time.

All players did receive a role pm, and it was during night-time. I typed in the --scan command and a target and nothing happened the bot didn't respond at all. People have said the same thing as the vigilante and the doctor. Also, the bomb role didn't kill the last person who voted them.

Here's a link to the chat if you want to see the bug for yourself: https://discord.gg/0127wKoRUWTQWuqK0

**Comment by foolmoron** [comment]
For future reference, the problem here was that @Bazinga9000 was using node.js v4 something and the bot requires at least v5.8.0. I updated the readme and package.json to emphasize this requirement.
